### ISSUE TITLE
Discussion regarding GSoC

### ISSUE THREAD

**Issue by Yashwants19** [Yashwants19/RcppMLPACK#1] opened 2020-04-11 10:24 UTC
Hey @rcurtin @eddelbuettel @zoq I have added some more hand written bindings(LARS, PCA). I have also added a function to Serialize the model to xml (testRBinding -- SerializeTestRBindingToXML, Lars --SerializeLARSToXML ) i.e. inspired from [#1709](https://github.com/mlpack/mlpack/issues/1709). I know the functionality (Serialize the model) still have to be improved a lot. But if you all agree we can add this to the stretch goals.
For testing you can go for:
```
library(RcppMLPACK)
Data = matrix(rexp(100, rate=.1), nrow=10)
Responses =matrix(rexp(10, rate=.1), nrow = 10)
test = matrix(rexp(100, rate=.1), nrow=10)
out1 <- Lars(Input=Data, Lambda1=0.4, Lambda2=0, Responses=Responses)
out2 <- Lars(InputModel=out1$outputModel, Test=test)
transform_model(out2$outputXml)
```
Thank You.

**Comment by eddelbuettel** [comment] 2020-04-11 18:03
I wasstill having problems with the repo and (correctly) suspected it might be because I am on an older MLPACK version (as packaged in Ubuntu) so I just updated my PPA to use the current version in Debian (and the next Ubuntu release).  That worked :)     

Also the issue I was nagging about still seeing `cerr` reference -- due to me being on MLPACK 3.0.*.  So we can ignore that. Yay!

(There is a call to `rand` somewhere we should replace with a call to R's RNG.   Otherwise it looks great!)

```sh
N  checking compiled code ...
   File ‘RcppMLPACK/libs/RcppMLPACK.so’:
     Found ‘rand’, possibly from ‘rand’ (C)
       Object: ‘RcppExports.o’
   
   Compiled code should not call entry points which might terminate R nor
   write to stdout/stderr instead of to the console, nor use Fortran I/O
   nor system RNGs.
   
   See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
```

Nice work!

**Comment by eddelbuettel** [comment] 2020-04-11 18:03
Oh, also poking @coatless

**Comment by eddelbuettel** [comment] 2020-04-11 19:02
Zong. Not really @Yashwants19's problem, more like @rcurtin _et al_:

```sh
edd@rob:~/git/rcppmlpack-gsos2020(master)$ ag -c -Q 'rand('       # rec. grep for 'rand('
src/mlpack/tests/recurrent_network_test.cpp:4
src/mlpack/tests/hmm_test.cpp:1
src/mlpack/tests/main_tests/hmm_viterbi_test.cpp:1
src/mlpack/core/tree/space_split/space_split_impl.hpp:1
src/mlpack/core/math/random.hpp:4
src/mlpack/methods/amf/termination_policies/validation_rmse_termination.hpp:2
edd@rob:~/git/rcppmlpack-gsos2020(master)$ 
```

Any chance would could stick `rand()` and `srand()` into a little `class` or `struct` and redefine / derive it when R is around to use R's RNGs?  (Armadillo does too, albeit with a bit of a hack we did years ago and ... which is still there.)

*Edit:* Had by oversight included the local copy of the sources I used for the PPA, so double counted. Fixed now.

**Comment by Yashwants19** [comment] 2020-04-12 06:09
> (There is a call to `rand` somewhere we should replace with a call to R's RNG. Otherwise it looks great!)
> 
> ```shell
> N  checking compiled code ...
>    File ‘RcppMLPACK/libs/RcppMLPACK.so’:
>      Found ‘rand’, possibly from ‘rand’ (C)
>        Object: ‘RcppExports.o’
>    
>    Compiled code should not call entry points which might terminate R nor
>    write to stdout/stderr instead of to the console, nor use Fortran I/O
>    nor system RNGs.
>    
>    See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
> ```

I have resolved this issue in [481d339](https://github.com/Yashwants19/RcppMLPACK/commit/481d3394ce80efd875c32faa82c78d201fc43e6e).
Thank You.

**Comment by eddelbuettel** [comment] 2020-04-12 14:12
Confirmed, it is _spotless_ now.  Nice work!

```sh
edd@rob:~/git/rcppmlpack-gsos2020(master)$ build.r       # helper script from littler
* checking for file ‘./DESCRIPTION’ ... OK       
* preparing ‘RcppMLPACK’:            
* checking DESCRIPTION meta-information ... OK
* cleaning src                                 
* running ‘cleanup’     
* installing the package to build vignettes
* creating vignettes ... OK        
* compacting vignettes and other PDF files       
* cleaning src                                                                                           
* running ‘cleanup’                   
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories                                                             
* building ‘RcppMLPACK_3.2.2.tar.gz’     
                                                                                                         
edd@rob:~/git/rcppmlpack-gsos2020(master)$ rcc.r RcppMLPACK_3.2.2.tar.gz    # ditto
── R CMD check ───────────────────────────-────────────────────────────────────────  
using log directory ‘/tmp/file51d6376308f8/RcppMLPACK.Rcheck’
─  using R version 3.6.3 (2020-02-29)                                                                    
─  using platform: x86_64-pc-linux-gnu (64-bit)
─  using session charset: UTF-8
✔  checking for file ‘RcppMLPACK/DESCRIPTION’ (635ms)
─  checking extension type ... Package         
─  this is package ‘RcppMLPACK’ version ‘3.2.2’
─  package encoding: UTF-8  
✔  checking package namespace information           
✔  checking package dependencies (665ms)
✔  checking if this is a source package ...
✔  checking if there is a namespace ...                                                                  
✔  checking for executable files (785ms)       
✔  checking for hidden files and directories ...
✔  checking for portable file names ...       
✔  checking for sufficient/correct file permissions ...
─  checking whether package ‘RcppMLPACK’ can be installed ... [15s/11s] OK (11.2s)
✔  checking installed package size      
✔  checking package directory
✔  checking ‘build’ directory
✔  checking DESCRIPTION meta-information ...
✔  checking top-level files
✔  checking for left-over files ...
✔  checking index information ...
✔  checking package subdirectories ...
✔  checking R files for non-ASCII characters ...
✔  checking R files for syntax errors ...
✔  checking whether the package can be loaded ...
✔  checking whether the package can be loaded with stated dependencies ...
✔  checking whether the package can be unloaded cleanly ...
✔  checking whether the namespace can be loaded with stated dependencies ...
✔  checking whether the namespace can be unloaded cleanly ...
✔  checking loading without being on the library search path ...
✔  checking dependencies in R code ...
✔  checking S3 generic/method consistency (439ms)
✔  checking replacement functions ...
✔  checking foreign function calls ...
✔  checking R code for possible problems (1.2s)
✔  checking Rd files ...
✔  checking Rd metadata ...
✔  checking Rd cross-references ...
✔  checking for missing documentation entries ...
✔  checking for code/documentation mismatches (680ms)
✔  checking Rd \usage sections (575ms)
✔  checking Rd contents ...
✔  checking for unstated dependencies in examples ...
✔  checking line endings in shell scripts
✔  checking line endings in C/C++/Fortran sources/headers ...
✔  checking line endings in Makefiles ...
✔  checking compilation flags in Makevars ...
✔  checking for GNU extensions in Makefiles
✔  checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS)
✔  checking compilation flags used ...
✔  checking compiled code ...
✔  checking sizes of PDF files under ‘inst/doc’ ...
✔  checking installed files from ‘inst/doc’ ...
✔  checking files in ‘vignettes’ ...
✔  checking examples (420ms)
✔  checking for unstated dependencies in ‘tests’ ...
─  checking tests ...
✔  Running ‘testthat.R’
✔  checking for unstated dependencies in vignettes ...
✔  checking package vignettes in ‘inst/doc’ ...
─  checking running R code from vignettes
     ‘RcppMLPACK-intro.Rnw’using ‘UTF-8’... OK
    NONE
✔  checking re-building of vignette outputs (1.5s)
✔  checking PDF version of manual (1.3s)
   
   
edd@rob:~/git/rcppmlpack-gsos2020(master)$

**Comment by rcurtin** [comment] 2020-04-13 13:16
@Yashwants19 nice work!  We should replace the calls to, e.g., `rand() % something` in the mlpack codebase (wherever they occur) with `mlpack::math::RandInt(something)` instead.  That will at least avoid the use of `rand()`; however, that doesn't completely fix the issue.

I think we will also have to port whatever the hack is for `ARMA_RNG_ALT` into mlpack too, but I don't totally understand what's done there.  @eddelbuettel any chance you can point me to somewhere where I can understand it better?  It looks like defining `ARMA_RNG_ALT` also expects a struct `arma::arma_rng_alt` to be defined, but I don't see that struct anywhere in the Armadillo codebase.  Is it supplied by RcppArmadillo or something?

**Comment by coatless** [comment] 2020-04-13 13:19
@rcurtin yes, `ARMA_RNG_ALT` is supplied by RcppArmadillo.

https://github.com/RcppCore/RcppArmadillo/blob/c9a1ddc2cc54fc72f8e79fea129eba3e040f1445/inst/include/RcppArmadilloForward.h#L41-L44

The implementation is here:

https://github.com/RcppCore/RcppArmadillo/blob/fd5c56d1c2a2fbd44790a3809aeee134d0f49818/inst/include/RcppArmadillo/Alt_R_RNG.h

That said, I think these lines just need to rely upon `Armadillo`'s underlying RNG functions as the alt rng define should automatically be used in such cases.

**Comment by rcurtin** [comment] 2020-04-13 13:24
@coatless thanks for the clarification.  Unfortunately I don't think that we can just replace mlpack's random number support (which appears in several places) with Armadillo's completely.  Or, at least, that would be a big task, since we generally use the mlpack RNG methods all over the place...

Here are the additional random number facilities that are used by mlpack:
https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/math/random.hpp

If we can cover both Armadillo via `ARMA_RNG_ALT` and then mlpack's bindings in some other way, that should suffice.  I wonder if it would work to, e.g., if `BINDING_TYPE` is `BINDING_TYPE_R`, then include some special `src/mlpack/bindings/r/r_random.hpp` file *instead of* `src/mlpack/core/math/random.hpp`, which exposes the same API except it uses R's RNG.  Maybe there's another way too; that's just one proposal.

**Comment by coatless** [comment] 2020-04-13 13:34
@rcurtin On the drawing side, I think that only a few small tweaks would be required. 
With respect to @Yashwants19 's work in https://github.com/Yashwants19/RcppMLPACK/commit/481d3394ce80efd875c32faa82c78d201fc43e6e, the change would need to be:

`rand()%elements` -> `arma::randi_val()` instead of the proposed `rand()%elements` -> `::Rf_runif()%elements` 

The other change that is probably more problematic and would require a `BINDING_TYPE_R` is setting a seed in _C++_ as this can only be done via R's `set.seed()` function. (Though, there is a fun ["hack" that works in non-parallel cases from _C++_](https://thecoatlessprofessor.com/programming/cpp/set-rs-seed-in-rcpp-sequential-case/) ). A better question is how often does MLPACK internally set a seed?

**Comment by eddelbuettel** [comment] 2020-04-13 13:38
@rcurtin It's all because R, written by (computational) statisticians for statisticians, cares a lot about its RNGs and its reproducibility.  Which always made sense from our end too, so now when you ask for N draws you get the same from R, from Rcpp (using R's generators of course) and, via the hack, from arma (for the main family, I think we are limited to uniform and normal).  

That is still a good approach in my book, and it would be nice to have it as an option for, say, RcppMLPACK.  Just how you can argue that having the same generator from R as in your executables matters.  Both views are "right" -- the user needs an option.  Maybe next year's GSoC could rethink this in a project.

Until then, having acccess to R's RNGs is one thing.  The other is to also turn off the nagging from `R CMD check`, and that we already have too thanks to the fine work by @Yashwants19.

**Comment by rcurtin** [comment] 2020-04-13 13:43
@coatless mlpack doesn't set a seed internally; only if `mlpack::math::RandomSeed()` is called.  But uses of, e.g., `mlpack::math::Random()` are strewn all throughout the codebase, and those mlpack's internal RNG facilities that I linked to (not Armadillo's, and not the `rand()` calls that @eddelbuettel's grep picked up).

Perhaps it would be possible to replace all of mlpack's implementations in `random.hpp` with calls directly to Armadillo's RNG functionality, but I'm not 100% sure that Armadillo's RNG functionality has everything that mlpack's does.  It has been a *very* long time since I checked.

@eddelbuettel thanks for the clarification.  Definitely this is an important point, and we should get mlpack to use R's RNG support in all cases.  Mostly my comments here are focused on how we can get that to work correctly---I'm in 100% agreement that it's a good goal.

Overall I'd consider mlpack's RNG support roughly equivalent to Armadillo's; basically it has some internal wrappers around C++ RNG facilities to provide "nicer" developer-facing functionality.  So we can certainly do something very similar to RcppArmadillo.

(Let me know if I misunderstood something.)

**Comment by eddelbuettel** [comment] 2020-04-13 13:48
Sounds good.  Everybody on the same page.  Conrad is of course doing the Right Thing (TM) as usual, relying on C++11 where he can.  What we hacked and whacked into it, and what still works, is that instead of `rand()` [which in its original implementation was in fact almost evil in how stupid it was, the Unix man pages still carry warnings too] we use R.  Which is slick.

And the same scheme of different choices, with a customizable compile-time preference which the R packages may steer towards R, is the way to go.  Research into all this has of course continued and there are other fine RNG frameworks out there. Some faster, some "better", many more modern for parallel streams.  We should support all those.  Eventually.

**Comment by Yashwants19** [comment] 2020-04-13 15:26
Hey, I am really sorry. I think so I had overlooked some thing previously the warnings was only created because of `arma_rng`. I have changed the code accordingly [f9baffb](https://github.com/Yashwants19/RcppMLPACK/commit/f9baffb71e71badaef3a5c908026b33d9daaeb3b).

Thank you all. :)

**Comment by Yashwants19** [comment] 2020-04-19 13:40
Hey all, As I discussed with Ryan and Dirk in my GSoC proposal about serialization. I have added some functionality regarding serialization from which we can serialize an mlpack R model to disk. I have also added a [test](https://github.com/Yashwants19/RcppMLPACK/blob/817cfcbeda4f4901bbb82aa70b0b3623e4feaca3/tests/testthat/test-R_binding.R#L59) for the same . Please guide me whether my approach is correct or not.
We can use the functionality as follows:
```
library(RcppMLPACK)
Data = matrix(rexp(100, rate=.1), nrow=10)
Responses =matrix(rexp(10, rate=.1), nrow = 10)
test = matrix(rexp(100, rate=.1), nrow=10)
out1 <- lars(input=Data, lambda1=0.4, lambda2=0, responses=Responses)
serialize_lars("model.bin", out1$output_model)
model = unserialize_lars("model.bin")
out2 <- lars(input_model=model, test=test)
serialize_lars_to_xml(model)
``` 
Thank You.

**Comment by Yashwants19** [comment] 2020-04-27 12:40
Hey @rcurtin I want to discuss about the directory structure of R Bindings. Should we include this package(RcppMLPACK) completely in mlpack which will live under src/bindings/R with the name `RcppMLPACK`, where we can directly auto-generate *.cpp files in `src` folder of RcppMLPACK and  *.R files in `R` folder of RcppMLPACK and further we also can auto-generate the `NAMESPACE` file (used to export the functions) using Cmake. By this approach we can ask Rcpp to build .so files on  its own and not by the help of Cmake. Or we just only use a simple `R` and `src` folder which we will be further copied in the respectively folder of the package and for testing it will be initially build using Cmake only. Using first approach we can test the bindings in azure pipeline with the help of `littler` packages or some other sources.

**Comment by eddelbuettel** [comment] 2020-04-27 12:51
Yes, we need to talk / should talk.  The (very) old MLPACK you started from used a `src/Makevars` inspired from another project, and it is not entirely correct. But I haven't had time to follow through.

There is in fact a few ways to do this, but they are "all advanced" (in the sense of we can't rely on system libraries -- and I actually wrote an entire tutorial paper-let on this: https://arxiv.org/abs/1911.06416).  

In short, one way is to (_e.g._ from `configure` which can be an executable script in ANY language, does not have to be created from `autoconf`) invoke `cmake` and create a static `libmlpack.a`.  Another is to (as you did) list the different *.o files and let R call `make` for you.   Similarly, the `Makefile` logic in `src/Makevars` _can_ make updating bindings another target that gets triggered.

You have already come an _amazingly_ far way and we haven't even started. It's really exciting, and once again congrats.  And please pardon my busyness and delayed replies...

**Comment by rcurtin** [comment] 2020-04-28 02:08
Nice! (about the serialization; sorry I didn't respond to that earlier)

Also, I have a bit of a side discussion with the name... the old bindings were called RcppMLPACK and may have reflected the very old all-caps "branding" of mlpack.  What should we do with the new package?  Should we just call it "mlpack"?  Or maybe "mlpackRcpp"?  "mlpackR"?  Mostly I want to just make sure that we can "match" the branding of the main library.  (For what it's worth, this is totally a lost battle.  It gets called MLpack, Mlpack, MLPACK, mLpAcK, anything you can think of,  ʞɔɐdʃɯ, whatever.  But I think that at least for "official" projects, we should try and match.)  Anyway, sorry for the diversion.  Maybe this isn't the right place to work that out, we can open a new issue if we like. :)

For the build process, there are a couple of advantages or disadvantages to either way.  For Python, it was impossible to get CMake to compile the Cython code, so I was forced to use setuptools.  That's an advantage because I know that the files will be compiled correctly for Cython (which changes regularly).  But the disadvantage is that I had to work really hard to make sure that the files were compiled with all of the right options, and that CMake would properly compute the dependency requirements for each target.  (In fact, I had to do some awful things in the `setup.py` so that each individual Python binding is buildable.  Blah.)

So, the same issues will apply if we use R to do the compilation and just supply the minimum possible.  Personally I might lean that way, if it's not too hard to make sure that we can get CFLAGS  and CXXFLAGS passed to R's build scripts.  It seems risky to depend on CMake for too much, since the way that R packages compile may change over time (and then we'd have to update our CMake configuration, and who knows how easy that would be?).

**Comment by coatless** [comment] 2020-04-28 02:32
Regarding the package name, the general convention when linking out to a library from Rcpp is to prefix it with Rcpp name, e.g. `RcppLibrary`. Mainly, this is a branding portion and immediately signals what to expect from a package. On this note, I think @thirdwing -- the current maintainer of _RcppMLPACK_ -- might be willing to let the `RcppMLPACK` name get released. But, this is a minor detail in a sea of more pressing matters. Let's revisit the topic when it is closer to listing the package on CRAN.

---

For the build process, I'm also in favor of placing as much weight on _R_'s build system as possible since that will likely lead to the least amount of resistance in listing the package on CRAN. 

Determining flags during the _R_ package build and installation procedure is only done for `OpenMP` :

https://github.com/Yashwants19/RcppMLPACK/blob/c66487323ee9039ff0380c63aa7244decc85abb4/configure.ac#L109-L127

Flags to the library are determined here: 

https://github.com/Yashwants19/RcppMLPACK/blob/c66487323ee9039ff0380c63aa7244decc85abb4/R/flags.R#L9-L39

With both of these in hand, they get inserted into an `inline` plugin defined that controls the compilation procedure for user-written code with the package.

https://github.com/Yashwants19/RcppMLPACK/blob/c66487323ee9039ff0380c63aa7244decc85abb4/R/inline.R#L1-L5

**Comment by eddelbuettel** [comment] 2020-04-28 02:46
Quick ones:

- Name: mostly a non-issue, the natural path would be to _replace_ RcppMLPACK on CRAN under that giving @thirdwing credit for the earlier work; I would not expect an issue.  And if by chance there is one we sort it out then.

- Builds:  CMake can be used; some R packages already do. But we can only use it to create a static library which is _then used by the normal R process_ in the link step.  R's build it pretty standardized and we should use as it much as we can.  And even rewrite what we have now if/when the setup changes. We'll be fine, this too should no be a holdup.

**Comment by thirdwing** [comment] 2020-04-28 02:54
I am totally fine to give the package name to the new maintainer.

Anything on my side needs to be done?

**Comment by eddelbuettel** [comment] 2020-04-28 03:34
Not yet. GSoC is only starting :)

**Comment by Yashwants19** [comment] 2020-04-28 13:40
Hi I am really sorry for such a late reply. Yesterday my WiFi crashed, by the help of some friend I am able to arrange Internet again in this "Lock-down".

By this conversation it seems that if possible then for building the package we must rely on Rcpp/R only.
Hey I am really sorry, I think so I must maintain a `ChangeLog` here.
> Yes, we need to talk / should talk. The (very) old MLPACK you started from used a src/Makevars  inspired from another project, and it is not entirely correct. But I haven't had time to follow through.

Now we are not using old(RcppMLPACK) Makevars file. I updated the file similar to Appendix 2: A Minimal src/Makevars (This paper is awesome I will definitely try to inherit this in our package :)). 

Now I think so for the directory structure I must follow the first approach only. 
If you all agree my next step should be to complete r_util.

Thank You.

**Comment by Yashwants19** [comment] 2020-04-29 14:35
Hey @eddelbuettel, If I am correct "eddelbuettel/BH" is not providing some header for serialization. As if boost-version is greater than 1.56 then there must be "unordered_map.hpp" and others present in it, but still for boost version 1.72 "eddelbuettel/BH" is not providing these headers. Is there any issue regarding the addition of these headers ? 
Please correct me If I am wrong.
Thank you

**Comment by eddelbuettel** [comment] 2020-04-29 14:40
Boost Serialization does not work, to the best of my knowledge, without linking.  Which is why Boost Serialization, like some other Boost libraries, is not part of the _header-only_ package BH.

Which is why I suggested to you to take "the delta" and include it in your RcppMLPACK package so that you can just complement what is missing from BH to arrive at working serialization via Boost.  Which you did.  

We can add other sub-components of Boost to BH _if they work header-only_.  Unordered map appears to be part of the set already:

```sh
edd@rob:~/git/bh(master)$ find . -name unordered_map.hpp
./inst/include/boost/unordered/unordered_map.hpp
./inst/include/boost/unordered_map.hpp
edd@rob:~/git/bh(master)$ 
```

I may have misunderstood or missed your question.  If so please clarify and expand.  Thanks!

**Comment by Yashwants19** [comment] 2020-04-29 15:01
You are correct you suggest to me add those files to the package only and it worked (you are great :)). But I was thinking that if "BH" provides all the headers then we can remove those files from the package, But this is not that important we can still add these files to the package only as "mlpack" was also providing these files for user which uses boost version less than 1.56.
I think so serialization is also providing its own "unordered_map.hpp",  "unordered_collections_save_imp.hpp", "unordered_collections_load_imp.hpp", etc. Please correct If I am wrong.
Thank You

**Comment by eddelbuettel** [comment] 2020-04-29 15:12
So the discussion is about possibly refining / reducing the set of files you have in your (excellent, by the way -- I had suggested in the past to others and few or none made it work) `boost/` tree?

I would not worry about a few files. I worry more about subtle bugs we may get if some versions skew between the BH (or system boost) used and your tree.  And I do not have an idea about how to test or check.  Other than waiting for bugs...    The best may just be to enfore BH and use Boost Serialization files from the same Boost release.

**Comment by rcurtin** [comment] 2020-06-09 19:22
Should we go ahead and close this issue since discussion seems to have moved to other issues?  (I might have overlooked any questions that are still being discussed, someone correct me if I did. :))

**Comment by coatless** [comment] 2020-06-09 19:24
Aye! The issue should be close as we've begun! 😄

**Comment by coatless** [comment] 2020-06-09 19:28
Closing this out. Thanks @Yashwants19  for collaborator status!

**Closed as completed by coatless** 2020-06-09 19:28 UTC
